apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/manifest.yaml
- upstream/extensions.yaml
- gvisor-runtimeclass.yaml
- sandboxes-namespace.yaml
- python-sandbox-template.yaml
