apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: lighttheham
  namespace: lighttheham
spec:
  selector:
    matchLabels:
      app: lighttheham
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - lighttheham
