apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atuin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: atuin
  project: default
  source:
    path: gitops/tools/apps/atuin
    repoURL: https://github.com/AlverezYari/phillips-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
