apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: exchange-rails-secrets
  namespace: tatl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: secret_key_base
    remoteRef:
      key: exchange-rails-config
      property: secret_key_base
