apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://utkuozdemir.org/helm-charts
    chart: filebrowser
    targetRevision: "1.0.3"
    helm:
      values: |-
        image:
          repository: filebrowser/filebrowser
          tag: v2.27.0
          pullPolicy: IfNotPresent
        
        nodeSelector:
          kubernetes.io/hostname: homelab-04
        
        rootDir:
          type: pvc
          pvc:
            existingClaim: "jellyfin-media"
        
        db:
          pvc:
            enabled: true
            storageClassName: "syno-iscsi-default"
            size: 1Gi
        
        service:
          type: ClusterIP
          port: 80
        
        ingress:
          enabled: false
        
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
    
  destination:
    server: https://kubernetes.default.svc
    namespace: media
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true