apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: v1.16.2
    path: .
    helm:
      values: |-
        persistence:
          persistentVolumeClaim:
            registry:
              size: "200Gi"
        expose:
          type: ingress
          tls:
            enabled: false
            certSource: none
          ingress:
            hosts:
              core: harbor.phillips-homelab.net
            className: cilium
            annotations:
              "kubernetes.io/ingress.class": "cilium"
              "ingress.kubernetes.io/force-ssl-redirect": "true"
              "nginx.ingress.kubernetes.io/proxy-body-size": null
              "nginx.ingress.kubernetes.io/ssl-redirect": null
        externalURL: https://harbor.phillips-homelab.net
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true


