apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goharbor/harbor-helm.git
    targetRevision: v1.16.2
    path: .
    helm:
      values: |-
        persistence:
          persistentVolumeClaim:
            registry:
              size: "200Gi"
        expose:
          type: ingress
          tls:
            enabled: true
          ingress:
            hosts:
              core: harbor.phillips-homelab.net
            className: cilium
            annotations:
              "ingress.kubernetes.io/force-ssl-redirect": "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true


