apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: webui_secret_key
    remoteRef:
      key: openwebui-config
      property: webui_secret_key