apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pixelflut
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: pixelflut
  project: default
  source:
    path: gitops/tools/apps/pixelflut
    repoURL: https://github.com/AlverezYari/phillips-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
