apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stock-bot-secrets
  namespace: stock-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    name: stock-bot-secrets
    creationPolicy: Owner
  data:
  - secretKey: alpaca_api_key
    remoteRef:
      key: stock-bot-alpaca
      property: api_key
  - secretKey: alpaca_secret_key
    remoteRef:
      key: stock-bot-alpaca
      property: secret_key
