apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: tailscale-config
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: tailscale-config
      property: client_secret
