apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zot-auth
  namespace: zot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: htpasswd
    remoteRef:
      key: zot-auth
      property: htpasswd
