apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-registry
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AlverezYari/fork-zot-helm-chart
    targetRevision: main
    path: charts/zot
    helm:
      values: |
        replicaCount: 1

        image:
          repository: ghcr.io/project-zot/zot-linux-amd64
          tag: "v2.1.2"
          pullPolicy: IfNotPresent

        persistence: true
        pvc:
          create: true
          accessModes: ["ReadWriteOnce"]
          storageClassName: syno-iscsi-default
          storage: 200Gi

        mountConfig: true
        mountSecret: true
        existingSecret: zot-auth

        ############################
        #        CONFIG FILE       #
        ############################
        configFiles:
          config.json: |-
            {
              "storage": {
                "rootDirectory": "/var/lib/registry",
                "dedupe": true,
                "gc": true,
                "gcDelay": "1h",
                "gcInterval": "24h"
              },
              "http": {
                "address": "0.0.0.0",
                "port": "5000",

                /* ---- BASIC AUTH FOR REAL USERS ---- */
                "auth": {
                  "htpasswd": {
                    "path": "/secret/htpasswd"
                  }
                },

                /* ---- OPEN JUST THE HEALTH ENDPOINT ---- */
                "accessControl": {
                  "anonymousPolicy": [ "read" ],
                  "exceptions": [
                    { "method": "GET", "regex": "^/v2/$" }
                  ]
                }
              },
              "log": { "level": "debug" }
            }

        service:
          type: ClusterIP
          port: 5000

        fullnameOverride: zot-registry

        # --- probes now need *no* header ---
        probeAuthFromSecret:
          enabled: false
        authHeader: ""

        # leave probe bodies as‑is; they hit /v2/
        startupProbe:
          httpGet:
            path: /v2/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: zot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

