apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlverezYari/phillips-homelab.git'
    targetRevision: HEAD
    # Path to the overlay folder
    path: 'gitops/kcl-modules/zot/overlays'
    plugin:
      name: kcl-v1.0
  destination:
    namespace: zot
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

