apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tool-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/tools/apps
    repoURL: https://github.com/AlverezYari/phillips-homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
