apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: cloudflare-tunnel
      property: tunnel_token
