apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-garage-backup
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging
  target:
    name: forgejo-garage-backup
    creationPolicy: Owner
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: forgejo-garage-backup
      property: access_key_id
  - secretKey: ACCESS_SECRET_KEY
    remoteRef:
      key: forgejo-garage-backup
      property: secret_access_key
