apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: forgejo-backups
  namespace: forgejo
spec:
  configuration:
    destinationPath: s3://forgejo-backups/
    endpointURL: http://garage.garage.svc:3900
    s3Credentials:
      accessKeyId:
        name: forgejo-garage-backup
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: forgejo-garage-backup
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: "7d"
