apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: blocky
  namespace: blocky
  labels:
    app: blocky
spec:
  selector:
    matchLabels:
      app: blocky
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - blocky
