apiVersion: v1
kind: Service
metadata:
  name: breakwater
  namespace: pixelflut
spec:
  type: LoadBalancer
  selector:
    app: breakwater
  ports:
    - name: pixelflut
      port: 1234
      targetPort: pixelflut
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: vnc
      protocol: TCP
    - name: web
      port: 8080
      targetPort: web
      protocol: TCP
