apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stock-bot-pg
  namespace: stock-bot
spec:
  instances: 1

  storage:
    storageClass: syno-iscsi-default
    size: 20Gi

  bootstrap:
    initdb:
      database: stock-bot
      owner: stock-bot

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
