apiVersion: v1
kind: Service
metadata:
  name: ergobars-board
  namespace: ergobars
  labels:
    app: ergobars-board
spec:
  selector:
    app: ergobars-board
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
