apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/core/apps
    repoURL: 'https://github.com/AlverezYari/phillips-homelab.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
