---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: gateways
spec:
  gatewayClassName: cilium
  listeners:
  - name: https-1
    protocol: HTTPS
    port: 443
    hostname: argocd.phillips-homelab.net
    tls:
      certificateRefs:
      - kind: Secret
        name: argocd-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-app-route-1
  namespace: gateways
spec:
  parentRefs:
  - name: tls-gateway
    sectionName: https-1
  hostnames:
  - argocd.phillips-homelab.net
  rules:
  - backendRefs:
    - name: argocd-server
      namespace: argocd
      port: 80
---

