apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lan-cloud-pool"
  namespace: kube-system
spec:
  blocks:
  - start: "192.168.10.191"
    stop: "192.168.10.193"
  serviceSelector:
    matchLabels:
      homelab: net01

