---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: gateways
spec:
  dnsNames:
  - argocd.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: argocd-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: gateways
spec:
  dnsNames:
  - monitoring.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: monitoring-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: gateways
spec:
  dnsNames:
  - harbor.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: harbor-tls
---


