---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
  namespace: gateways
spec:
  dnsNames:
  - home-assistant.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: home-assistant-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: gateways
spec:
  dnsNames:
  - argocd.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: argocd-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: gateways
spec:
  dnsNames:
  - monitoring.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: monitoring-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-tls
  namespace: gateways
spec:
  dnsNames:
  - zot.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: zot-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: gateways
spec:
  dnsNames:
  - jellyfin.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: jellyfin-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-tls
  namespace: gateways
spec:
  dnsNames:
  - files.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: filebrowser-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwebui-tls
  namespace: gateways
spec:
  dnsNames:
  - openwebui.phillips-homelab.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: openwebui-tls
---


