apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://opensource.ncsa.illinois.edu/charts/
    chart: garage
    targetRevision: "0.9.1"
    helm:
      values: |-
        garage:
          # Use custom TOML to include admin token for API access
          garageTomlString: |
            metadata_dir = "/mnt/meta"
            data_dir = "/mnt/data"
            db_engine = "lmdb"
            block_size = 1048576
            replication_factor = 1
            consistency_mode = "consistent"
            compression_level = 1
            rpc_bind_addr = "[::]:3901"
            rpc_secret = "__RPC_SECRET_REPLACE__"
            bootstrap_peers = []

            [kubernetes_discovery]
            namespace = "garage"
            service_name = "garage"
            skip_crd = false

            [s3_api]
            s3_region = "garage"
            api_bind_addr = "[::]:3900"
            root_domain = ".s3.garage.local"

            [s3_web]
            bind_addr = "[::]:3902"
            root_domain = ".web.garage.local"
            index = "index.html"

            [admin]
            api_bind_addr = "[::]:3903"
            admin_token = "fedf959894dc2247837d4ae54783ac239e0aae4c7f6ba9e39ef094e5c0f3a2b1"

        persistence:
          enabled: true
          meta:
            storageClass: "syno-iscsi-default"
            size: 1Gi
          data:
            storageClass: "syno-iscsi-default"
            size: 20Gi

        deployment:
          kind: StatefulSet
          replicaCount: 1
          podManagementPolicy: OrderedReady

        service:
          type: ClusterIP
          s3:
            api:
              port: 3900
            web:
              port: 3902
          rpc:
            port: 3901

        ingress:
          s3:
            enabled: false
          web:
            enabled: false

        monitoring:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: garage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
