---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-home-assistant-service
  namespace: home-assistant
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gateways
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-monitoring-service
  namespace: monitoring
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gateways
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-argocd-service
  namespace: argocd
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gateways
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-zot-service
  namespace: zot
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gateways
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: gateways
spec:
  gatewayClassName: cilium
  listeners:
  - name: https-1
    protocol: HTTPS
    port: 443
    hostname: argocd.phillips-homelab.net
    tls:
      certificateRefs:
      - kind: Secret
        name: argocd-tls
  - name: https-2
    protocol: HTTPS
    port: 443
    hostname: monitoring.phillips-homelab.net
    tls:
      certificateRefs:
      - kind: Secret
        name: monitoring-tls
  - name: https-3
    protocol: HTTPS
    port: 443
    hostname: zot.phillips-homelab.net
    tls:
      certificateRefs:
      - kind: Secret
        name: zot-tls
  - name: https-4
    protocol: HTTPS
    port: 443
    hostname: home-assistant.phillips-homelab.net
    tls:
      certificateRefs:
      - kind: Secret
        name: home-assistant-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-app-route-1
  namespace: gateways
spec:
  parentRefs:
  - name: tls-gateway
    sectionName: https-1
  hostnames:
  - argocd.phillips-homelab.net
  rules:
  - backendRefs:
    - name: argocd-server
      namespace: argocd
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-app-route-2
  namespace: gateways
spec:
  parentRefs:
  - name: tls-gateway
    sectionName: https-2
    namespace: gateways
  hostnames:
  - monitoring.phillips-homelab.net
  rules:
  - backendRefs:
    - name: grafana
      namespace: monitoring
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-app-route-3
  namespace: gateways
spec:
  parentRefs:
  - name: tls-gateway
    sectionName: https-3
    namespace: gateways
  hostnames:
  - zot.phillips-homelab.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v2
    - path:
        type: Exact
        value: /
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set:
            - name: Authorization
              value: "{http.request.header.authorization}"
    backendRefs:
    - name: zot-registry
      namespace: zot
      port: 5000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-app-route-4
  namespace: gateways
spec:
  parentRefs:
  - name: tls-gateway
    sectionName: https-4
    namespace: gateways
  hostnames:
  - home-assistant.phillips-homelab.net
  rules:
  - backendRefs:
    - name: home-assistant
      namespace: home-assistant
      port: 8123
---
