apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.29.0
    helm:
      values: |
        global:
          extraArgs:
            - -config.expand-env=true
          extraEnvFrom:
            - secretRef:
                name: garage-s3-credentials

        deploymentMode: SimpleScalable

        loki:
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: "loki_index_"
                  period: "24h"
          ingester:
            chunk_encoding: snappy
          querier:
            max_concurrent: 4
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          storage:
            type: s3
            s3:
              endpoint: garage.garage.svc:3900
              region: garage
              secretAccessKey: ${secret_access_key}
              accessKeyId: ${access_key_id}
              s3ForcePathStyle: true
              insecure: true
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: chunks

        backend:
          replicas: 2
          extraArgs:
            - -target=all
        read:
          replicas: 2
        write:
          replicas: 0

        # Optimize cache sizes for homelab
        chunksCache:
          enabled: true
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 200m

        resultsCache:
          enabled: true
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m

        minio:
          enabled: false
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
