apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data
    - group: policy
      kind: PodDisruptionBudget
      jsonPointers:
        - /spec
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.29.0
    helm:
      values: |
        deploymentMode: SimpleScalable

        loki:
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: "loki_index_"
                  period: "24h"
          ingester:
            chunk_encoding: snappy
          querier:
            max_concurrent: 4
          pattern_ingester:
            enabled: true
          compactor:
            retention_enabled: true
            delete_request_store: s3
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
            retention_period: 720h
          storage:
            type: s3
            s3:
              endpoint: garage.garage.svc:3900
              region: garage
              secretAccessKey: ${secret_access_key}
              accessKeyId: ${access_key_id}
              s3ForcePathStyle: true
              insecure: true
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: chunks

        backend:
          replicas: 2
          extraArgs:
            - -target=all
            - -config.expand-env=true
          extraEnvFrom:
            - secretRef:
                name: garage-s3-credentials
        read:
          replicas: 2
          extraArgs:
            - -config.expand-env=true
          extraEnvFrom:
            - secretRef:
                name: garage-s3-credentials
        write:
          replicas: 0

        # Optimize cache sizes for homelab
        chunksCache:
          enabled: true
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 200m

        resultsCache:
          enabled: true
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m

        minio:
          enabled: false
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
