apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      values: |
        monitoring:
          dashboards:
            enabled: true
            namespace: monitoring
        loki:
          server:
            log_level: warn
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
              admin_api_directory: /var/loki/admin
          schemaConfig:
            configs:
              - from: 2025-04-25
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        persistence:
          enabled: true
          size: 10Gi
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

